### ISSUE TITLE
Uncaught Error: Class 'WpMinions\Plugin' not found

### ISSUE THREAD

**Issue by kish2011** [10up/WP-Minions#46]
**Uncaught Error: Class 'WpMinions\Plugin' not found**

Getting these errors when I am trying to call *wp_async_task_add*  this?
---
Fatal error: Uncaught Error: Class 'WpMinions\Plugin' not found in /Applications/MAMP/htdocs/woocommerce/wp-content/plugins/WP-Minions/wp-minions.php:30 Stack trace: #0 /Applications/MAMP/htdocs/woocommerce/wp-content/plugins/WP-Minions/wp-minions.php(64): wp_async_task_add('transition_post...', Array) #1 /Applications/MAMP/htdocs/woocommerce/wp-settings.php(362): include_once('/Applications/M...') #2 /Applications/MAMP/htdocs/woocommerce/wp-config.php(103): require_once('/Applications/M...') #3 /Applications/MAMP/htdocs/woocommerce/wp-load.php(37): require_once('/Applications/M...') #4 /Applications/MAMP/htdocs/woocommerce/wp-admin/admin.php(34): require_once('/Applications/M...') #5 /Applications/MAMP/htdocs/woocommerce/wp-admin/plugins.php(10): require_once('/Applications/M...') #6 {main} thrown in /Applications/MAMP/htdocs/woocommerce/wp-content/plugins/WP-Minions/wp-minions.php on line 30
--

**Comment by jeffpaul** [comment]
@kish2011 thanks for the feedback and the related PR!  I've milestoned this for the next release and we'll get back to you with any questions after the PR gets through code review.
